/* ---------- 2) PRODUCTS (상품) ---------- */
CREATE TABLE PRODUCTS (
  PRODUCT_ID      NUMBER              CONSTRAINT PK_PRODUCTS PRIMARY KEY,
  PRODUCT_NAME    VARCHAR2(120)       CONSTRAINT NN_PRODUCTS_NAME NOT NULL,
  PRICE           NUMBER(10,0)        CONSTRAINT CK_PRODUCTS_PRICE CHECK (PRICE >= 0),
  DISCOUNT_RATE   NUMBER(3,0)         DEFAULT 0
                                     CONSTRAINT CK_PRODUCTS_DISC CHECK (DISCOUNT_RATE BETWEEN 0 AND 100),
  CATEGORY        VARCHAR2(60),
  IMAGE_URL       VARCHAR2(300),
  DESCRIPTION     CLOB,
  CREATED_AT      DATE                DEFAULT SYSDATE,
  STATUS          VARCHAR2(10)        DEFAULT 'SALE'
                                     CONSTRAINT CK_PRODUCTS_STATUS CHECK (STATUS IN ('SALE','HIDE','OUT'))